# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# NOTE! THIS FILE IS AUTOMATICALLY GENERATED AND WILL BE OVERWRITTEN!
#
# IF YOU WANT TO MODIFY THIS FILE, YOU SHOULD MODIFY THE TEMPLATE
# `get_provider_info_TEMPLATE.py.jinja2` IN the `dev/breeze/src/airflow_breeze/templates` DIRECTORY


def get_provider_info():
    return {
        "package-name": "apache-airflow-providers-apache-hamilton",
        "name": "Apache Hamilton",
        "description": "Execute reusable `Apache Hamilton <https://hamilton.apache.org/>`__ transformations inside Airflow tasks.\n\n.. note::\n\n   This provider has not been released. Version ``1.0.0`` is the planned first release.\n   The generated publication, documentation, and download links below are placeholders;\n   their release artifacts are not available. Until publication, install a wheel built\n   from a source checkout containing this provider.\n",
        "integrations": [
            {
                "integration-name": "Apache Hamilton",
                "external-doc-url": "https://hamilton.apache.org/",
                "how-to-guide": ["/docs/apache-airflow-providers-apache-hamilton/operators/hamilton.rst"],
                "tags": ["apache"],
            }
        ],
        "operators": [
            {
                "integration-name": "Apache Hamilton",
                "python-modules": ["airflow.providers.apache.hamilton.operators.hamilton"],
            }
        ],
        "task-decorators": [
            {
                "class-name": "airflow.providers.apache.hamilton.decorators.hamilton.hamilton_task",
                "name": "hamilton",
            }
        ],
    }
